---
- hosts: all
  become: true
  tasks:

  - name: Install python3
    apt: 
      name: python3
      state: latest

  - name: Install pip3
    apt: 
      name: python3-pip
      state: latest

  - name: Remove existing python links
    command: rm /usr/bin/python

  - name: Use python3 as default
    command: ln -s /usr/bin/python3 /usr/bin/python

  - name: Remove existing pip links
    command: rm /usr/bin/pip

  - name: Use pip3 as default
    command: ln -s /usr/bin/pip3 /usr/bin/pip

  - name: Install Java open-jdk
    apt:
      name: openjdk-21-jdk
      state: latest
  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: latest
